export interface LanguageItem {
  id: string;
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  region: "Americas" | "Europe" | "Asia & Pacific" | "Middle East" | "Africa";
  popularRank?: number;
}

export const FAMOUS_100_LANGUAGES: LanguageItem[] = [
  // Top Global & Americas
  { id: "en-US", code: "en-US", name: "English (US)", nativeName: "English", flag: "🇺🇸", region: "Americas", popularRank: 1 },
  { id: "en-GB", code: "en-GB", name: "English (UK)", nativeName: "English", flag: "🇬🇧", region: "Europe", popularRank: 2 },
  { id: "en-CA", code: "en-CA", name: "English (Canada)", nativeName: "English", flag: "🇨🇦", region: "Americas" },
  { id: "en-AU", code: "en-AU", name: "English (Australia)", nativeName: "English", flag: "🇦🇺", region: "Asia & Pacific" },
  { id: "es-ES", code: "es-ES", name: "Spanish (Spain)", nativeName: "Español", flag: "🇪🇸", region: "Europe", popularRank: 3 },
  { id: "es-MX", code: "es-MX", name: "Spanish (Mexico)", nativeName: "Español", flag: "🇲🇽", region: "Americas", popularRank: 4 },
  { id: "es-US", code: "es-US", name: "Spanish (Latin America)", nativeName: "Español Latino", flag: "🌎", region: "Americas" },
  { id: "pt-BR", code: "pt-BR", name: "Portuguese (Brazil)", nativeName: "Português", flag: "🇧🇷", region: "Americas", popularRank: 9 },
  { id: "pt-PT", code: "pt-PT", name: "Portuguese (Portugal)", nativeName: "Português", flag: "🇵🇹", region: "Europe" },
  { id: "fr-FR", code: "fr-FR", name: "French (France)", nativeName: "Français", flag: "🇫🇷", region: "Europe", popularRank: 7 },
  { id: "fr-CA", code: "fr-CA", name: "French (Canada)", nativeName: "Français Canadien", flag: "🇨🇦", region: "Americas" },

  // Asia & Pacific
  { id: "zh-CN", code: "zh-CN", name: "Mandarin Chinese (Simplified)", nativeName: "简体中文", flag: "🇨🇳", region: "Asia & Pacific", popularRank: 5 },
  { id: "zh-TW", code: "zh-TW", name: "Mandarin Chinese (Traditional)", nativeName: "繁體中文", flag: "🇹🇼", region: "Asia & Pacific" },
  { id: "zh-HK", code: "zh-HK", name: "Cantonese", nativeName: "廣東話", flag: "🇭🇰", region: "Asia & Pacific" },
  { id: "hi-IN", code: "hi-IN", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳", region: "Asia & Pacific", popularRank: 6 },
  { id: "ur-PK", code: "ur-PK", name: "Urdu", nativeName: "اردو", flag: "🇵🇰", region: "Asia & Pacific", popularRank: 10 },
  { id: "bn-BD", code: "bn-BD", name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩", region: "Asia & Pacific", popularRank: 8 },
  { id: "ja-JP", code: "ja-JP", name: "Japanese", nativeName: "日本語", flag: "🇯🇵", region: "Asia & Pacific", popularRank: 11 },
  { id: "ko-KR", code: "ko-KR", name: "Korean", nativeName: "한국어", flag: "🇰🇷", region: "Asia & Pacific", popularRank: 12 },
  { id: "vi-VN", code: "vi-VN", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳", region: "Asia & Pacific", popularRank: 14 },
  { id: "id-ID", code: "id-ID", name: "Indonesian (Bahasa)", nativeName: "Bahasa Indonesia", flag: "🇮🇩", region: "Asia & Pacific" },
  { id: "ms-MY", code: "ms-MY", name: "Malay", nativeName: "Bahasa Melayu", flag: "🇲🇾", region: "Asia & Pacific" },
  { id: "th-TH", code: "th-TH", name: "Thai", nativeName: "ไทย", flag: "🇹🇭", region: "Asia & Pacific" },
  { id: "tl-PH", code: "tl-PH", name: "Tagalog (Filipino)", nativeName: "Filipino", flag: "🇵🇭", region: "Asia & Pacific" },
  { id: "pa-IN", code: "pa-IN", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ / پنجابی", flag: "🇮🇳", region: "Asia & Pacific" },
  { id: "mr-IN", code: "mr-IN", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳", region: "Asia & Pacific" },
  { id: "te-IN", code: "te-IN", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳", region: "Asia & Pacific" },
  { id: "ta-IN", code: "ta-IN", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳", region: "Asia & Pacific" },
  { id: "gu-IN", code: "gu-IN", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳", region: "Asia & Pacific" },
  { id: "kn-IN", code: "kn-IN", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳", region: "Asia & Pacific" },
  { id: "ml-IN", code: "ml-IN", name: "Malayalam", nativeName: "മലയാളം", flag: "🇮🇳", region: "Asia & Pacific" },
  { id: "or-IN", code: "or-IN", name: "Odia", nativeName: "ଓଡ଼ିଆ", flag: "🇮🇳", region: "Asia & Pacific" },
  { id: "my-MM", code: "my-MM", name: "Burmese", nativeName: "မြန်မာစာ", flag: "🇲🇲", region: "Asia & Pacific" },
  { id: "km-KH", code: "km-KH", name: "Khmer", nativeName: "ភាសាខ្មែរ", flag: "🇰🇭", region: "Asia & Pacific" },
  { id: "ne-NP", code: "ne-NP", name: "Nepali", nativeName: "नेपाली", flag: "🇳🇵", region: "Asia & Pacific" },
  { id: "si-LK", code: "si-LK", name: "Sinhala", nativeName: "සිංහල", flag: "🇱🇰", region: "Asia & Pacific" },
  { id: "su-ID", code: "su-ID", name: "Sundanese", nativeName: "Basa Sunda", flag: "🇮🇩", region: "Asia & Pacific" },
  { id: "jv-ID", code: "jv-ID", name: "Javanese", nativeName: "Basa Jawa", flag: "🇮🇩", region: "Asia & Pacific" },
  { id: "lo-LA", code: "lo-LA", name: "Lao", nativeName: "ພາສາລາວ", flag: "🇱🇦", region: "Asia & Pacific" },
  { id: "mn-MN", code: "mn-MN", name: "Mongolian", nativeName: "Монгол хэл", flag: "🇲🇳", region: "Asia & Pacific" },
  { id: "dz-BT", code: "dz-BT", name: "Dzongkha (Bhutanese)", nativeName: "རྫོང་ཁ", flag: "🇧🇹", region: "Asia & Pacific" },
  { id: "bo-CN", code: "bo-CN", name: "Tibetan", nativeName: "བོད་སྐད", flag: "🇨🇳", region: "Asia & Pacific" },
  { id: "sd-PK", code: "sd-PK", name: "Sindhi", nativeName: "سنڌي", flag: "🇵🇰", region: "Asia & Pacific" },
  { id: "skr-PK", code: "skr-PK", name: "Saraiki", nativeName: "سرائیکی", flag: "🇵🇰", region: "Asia & Pacific" },
  { id: "ps-AF", code: "ps-AF", name: "Pashto", nativeName: "پښتو", flag: "🇦🇫", region: "Asia & Pacific" },

  // Middle East & West Asia
  { id: "ar-SA", code: "ar-SA", name: "Arabic (Saudi / Gulf)", nativeName: "العربية", flag: "🇸🇦", region: "Middle East", popularRank: 13 },
  { id: "ar-EG", code: "ar-EG", name: "Arabic (Egyptian)", nativeName: "العربية المصرية", flag: "🇪🇬", region: "Middle East" },
  { id: "ar-AE", code: "ar-AE", name: "Arabic (UAE / Dubai)", nativeName: "العربية الخليجية", flag: "🇦🇪", region: "Middle East" },
  { id: "ar-LB", code: "ar-LB", name: "Arabic (Levantine)", nativeName: "العربية الشامية", flag: "🇱🇧", region: "Middle East" },
  { id: "fa-IR", code: "fa-IR", name: "Persian (Farsi)", nativeName: "فارسی", flag: "🇮🇷", region: "Middle East" },
  { id: "tr-TR", code: "tr-TR", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷", region: "Middle East", popularRank: 15 },
  { id: "he-IL", code: "he-IL", name: "Hebrew", nativeName: "עברית", flag: "🇮🇱", region: "Middle East" },
  { id: "ku-IQ", code: "ku-IQ", name: "Kurdish (Kurmanji / Sorani)", nativeName: "Kurdî / کوردی", flag: "🇮🇶", region: "Middle East" },
  { id: "az-AZ", code: "az-AZ", name: "Azerbaijani", nativeName: "Azərbaycan dili", flag: "🇦🇿", region: "Middle East" },
  { id: "hy-AM", code: "hy-AM", name: "Armenian", nativeName: "Հայերեն", flag: "🇦🇲", region: "Middle East" },
  { id: "ka-GE", code: "ka-GE", name: "Georgian", nativeName: "ქართული", flag: "🇬🇪", region: "Middle East" },

  // Europe
  { id: "de-DE", code: "de-DE", name: "German (Germany)", nativeName: "Deutsch", flag: "🇩🇪", region: "Europe", popularRank: 16 },
  { id: "de-AT", code: "de-AT", name: "German (Austria & Swiss)", nativeName: "Österreichisches Deutsch", flag: "🇦🇹", region: "Europe" },
  { id: "it-IT", code: "it-IT", name: "Italian", nativeName: "Italiano", flag: "🇮🇹", region: "Europe", popularRank: 17 },
  { id: "ru-RU", code: "ru-RU", name: "Russian", nativeName: "Русский", flag: "🇷🇺", region: "Europe", popularRank: 18 },
  { id: "nl-NL", code: "nl-NL", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱", region: "Europe" },
  { id: "nl-BE", code: "nl-BE", name: "Flemish (Belgian Dutch)", nativeName: "Vlaams", flag: "🇧🇪", region: "Europe" },
  { id: "pl-PL", code: "pl-PL", name: "Polish", nativeName: "Polski", flag: "🇵🇱", region: "Europe" },
  { id: "uk-UA", code: "uk-UA", name: "Ukrainian", nativeName: "Українська", flag: "🇺🇦", region: "Europe" },
  { id: "el-GR", code: "el-GR", name: "Greek", nativeName: "Ελληνικά", flag: "🇬🇷", region: "Europe" },
  { id: "cs-CZ", code: "cs-CZ", name: "Czech", nativeName: "Čeština", flag: "🇨🇿", region: "Europe" },
  { id: "ro-RO", code: "ro-RO", name: "Romanian", nativeName: "Română", flag: "🇷🇴", region: "Europe" },
  { id: "hu-HU", code: "hu-HU", name: "Hungarian", nativeName: "Magyar", flag: "🇭🇺", region: "Europe" },
  { id: "sv-SE", code: "sv-SE", name: "Swedish", nativeName: "Svenska", flag: "🇸🇪", region: "Europe" },
  { id: "da-DK", code: "da-DK", name: "Danish", nativeName: "Dansk", flag: "🇩🇰", region: "Europe" },
  { id: "fi-FI", code: "fi-FI", name: "Finnish", nativeName: "Suomi", flag: "🇫🇮", region: "Europe" },
  { id: "no-NO", code: "no-NO", name: "Norwegian", nativeName: "Norsk", flag: "🇳🇴", region: "Europe" },
  { id: "sk-SK", code: "sk-SK", name: "Slovak", nativeName: "Slovenčina", flag: "🇸🇰", region: "Europe" },
  { id: "bg-BG", code: "bg-BG", name: "Bulgarian", nativeName: "Български", flag: "🇧🇬", region: "Europe" },
  { id: "sr-RS", code: "sr-RS", name: "Serbian", nativeName: "Српски", flag: "🇷🇸", region: "Europe" },
  { id: "hr-HR", code: "hr-HR", name: "Croatian", nativeName: "Hrvatski", flag: "🇭🇷", region: "Europe" },
  { id: "bs-BA", code: "bs-BA", name: "Bosnian", nativeName: "Bosanski", flag: "🇧🇦", region: "Europe" },
  { id: "sq-AL", code: "sq-AL", name: "Albanian", nativeName: "Shqip", flag: "🇦🇱", region: "Europe" },
  { id: "lt-LT", code: "lt-LT", name: "Lithuanian", nativeName: "Lietuvių", flag: "🇱🇹", region: "Europe" },
  { id: "lv-LV", code: "lv-LV", name: "Latvian", nativeName: "Latviešu", flag: "🇱🇻", region: "Europe" },
  { id: "et-EE", code: "et-EE", name: "Estonian", nativeName: "Eesti", flag: "🇪🇪", region: "Europe" },
  { id: "sl-SI", code: "sl-SI", name: "Slovenian", nativeName: "Slovenščina", flag: "🇸🇮", region: "Europe" },
  { id: "mk-MK", code: "mk-MK", name: "Macedonian", nativeName: "Македонски", flag: "🇲🇰", region: "Europe" },
  { id: "ga-IE", code: "ga-IE", name: "Irish (Gaeilge)", nativeName: "Gaeilge", flag: "🇮🇪", region: "Europe" },
  { id: "cy-GB", code: "cy-GB", name: "Welsh (Cymraeg)", nativeName: "Cymraeg", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", region: "Europe" },
  { id: "is-IS", code: "is-IS", name: "Icelandic", nativeName: "Íslenska", flag: "🇮🇸", region: "Europe" },
  { id: "ca-ES", code: "ca-ES", name: "Catalan", nativeName: "Català", flag: "🇪🇸", region: "Europe" },
  { id: "eu-ES", code: "eu-ES", name: "Basque", nativeName: "Euskara", flag: "🇪🇸", region: "Europe" },
  { id: "gl-ES", code: "gl-ES", name: "Galician", nativeName: "Galego", flag: "🇪🇸", region: "Europe" },
  { id: "mt-MT", code: "mt-MT", name: "Maltese", nativeName: "Malti", flag: "🇲🇹", region: "Europe" },
  { id: "lb-LU", code: "lb-LU", name: "Luxembourgish", nativeName: "Lëtzebuergesch", flag: "🇱🇺", region: "Europe" },
  { id: "be-BY", code: "be-BY", name: "Belarusian", nativeName: "Беларуская", flag: "🇧🇾", region: "Europe" },

  // Africa
  { id: "sw-KE", code: "sw-KE", name: "Swahili", nativeName: "Kiswahili", flag: "🇰🇪", region: "Africa", popularRank: 19 },
  { id: "am-ET", code: "am-ET", name: "Amharic", nativeName: "አማርኛ", flag: "🇪🇹", region: "Africa" },
  { id: "ha-NG", code: "ha-NG", name: "Hausa", nativeName: "Harshen Hausa", flag: "🇳🇬", region: "Africa" },
  { id: "yo-NG", code: "yo-NG", name: "Yoruba", nativeName: "Èdè Yorùbá", flag: "🇳🇬", region: "Africa" },
  { id: "ig-NG", code: "ig-NG", name: "Igbo", nativeName: "Asụsụ Igbo", flag: "🇳🇬", region: "Africa" },
  { id: "zu-ZA", code: "zu-ZA", name: "Zulu", nativeName: "isiZulu", flag: "🇿🇦", region: "Africa" },
  { id: "xh-ZA", code: "xh-ZA", name: "Xhosa", nativeName: "isiXhosa", flag: "🇿🇦", region: "Africa" },
  { id: "af-ZA", code: "af-ZA", name: "Afrikaans", nativeName: "Afrikaans", flag: "🇿🇦", region: "Africa" },
  { id: "so-SO", code: "so-SO", name: "Somali", nativeName: "Af-Soomaali", flag: "🇸🇴", region: "Africa" },
  { id: "om-ET", code: "om-ET", name: "Oromo", nativeName: "Afaan Oromoo", flag: "🇪🇹", region: "Africa" },
  { id: "ti-ET", code: "ti-ET", name: "Tigrinya", nativeName: "ትግርኛ", flag: "🇪🇹", region: "Africa" },
  { id: "rw-RW", code: "rw-RW", name: "Kinyarwanda", nativeName: "Ikinyarwanda", flag: "🇷🇼", region: "Africa" },
  { id: "mg-MG", code: "mg-MG", name: "Malagasy", nativeName: "Fiteny Malagasy", flag: "🇲🇬", region: "Africa" },
  { id: "sn-ZW", code: "sn-ZW", name: "Shona", nativeName: "chiShona", flag: "🇿🇼", region: "Africa" },
  { id: "ff-SN", code: "ff-SN", name: "Fula (Fulani)", nativeName: "Fulfulde", flag: "🇸🇳", region: "Africa" },
];
